"""Add locked column to User model

Revision ID: 668d302d0168
Revises: 98274240dc23
Create Date: 2025-03-30 21:42:17.137793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668d302d0168'
down_revision = '98274240dc23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked')

    # ### end Alembic commands ###
