"""Add download counters to File model

Revision ID: 7d2c5346c599
Revises: 668d302d0168
Create Date: 2025-03-31 10:19:24.334001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2c5346c599'
down_revision = '668d302d0168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_downloads', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timestamp_downloads', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('signature_downloads', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('signature_downloads')
        batch_op.drop_column('timestamp_downloads')
        batch_op.drop_column('file_downloads')

    # ### end Alembic commands ###
