"""Add status field to File model

Revision ID: 98274240dc23
Revises: 9e3b8cf29f30
Create Date: 2025-03-30 21:01:10.048241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98274240dc23'
down_revision = '9e3b8cf29f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
